eddy/__main__.py, eddy/core/application.py, eddy/core/exporters/owl2.py, eddy/core/jvm.py, eddy/core/project.py, eddy/plugins/Explanation-Explorerv0.1/Explanation_explorer.py, eddy/reasoners/HermiT/HermiT.py, eddy/ui/ontology_consistency_check.py, requirements.txt, requirements/base.txt, requirements/cython.txt, setup.py, tests/__init__.py, tests/test_export.py
This new API allows application modules to abstract from the specific JNI bridging libraries. Currently supported libraries are jnius and jpype.
Also, move the application entry point inside the application package (in preparation for a migration to setuptools) and gracefully deal with the situation where a JRE is not found on the system.
=> JVM API to abstract from Java bridging libraries

.gitmodules, requirements-dev.txt, requirements/packaging.in, setup.py, support/dmgbuild/settings.py
Starting from macOS 10.14, the create-dmg script requires user intervention when creating disk images due to the new security restrictions on macOS and their use of applescript to generate the .DS_Store file inside the disk image. This makes it impossible without workarounds to run it in a ci environment such as that of travis.
This pull request changes the .dmg creation step from using create-dmg to using dmgbuild, a python module that still relies on hciutil to build the disk image, but uses the ds_store python module to create the directory service store file without resorting to Finder, and thus circumventing the user permission request and allowing the use of macOS 10.14+ as the host for automated builds.
This also gets rid of the createdmg submodule as it is not needed anymore.
=> Move from create-dmg to dmgbuild for .dmg creation on macOS

eddy/core/owl.py, eddy/plugins/ontology-explorer/ontology_explorer.py
Questa pull request è una proposta di soluzione al problema dell'inefficienza attuale dell'ontology explorer che causa il blocco dell'interfaccia grafica in fase di caricamento di un progetto ed in fase di cambio della modalità di rendering delle IRI, che per progetti di dimensioni non banali può durare anche minuti a quanto pare (vedi #124).
Il problema è causato dall'elevato costo della funzione `iriLabelString(iri)`, che viene chiamata diverse volte ad ogni inserimento/modifica di un nodo dal progetto. Facendo dei test ho riscontrato che di fatto non è l'ordinamento degli item nell'explorer a causare il blocco dell'interfaccia, in quanto di fatto eliminandolo si hanno differenze di tempo trascurabili,
quanto più la combinazione delle chiamate sincrone a `iriLabelString(iri)` durante la …
=> Fix inefficiency in ontology explorer rendering

.github/workflows/builds.yml, docs/dev.md, docs/install.md, requirements/in/packaging.in, requirements/out/requirements-py36-linux.txt, requirements/out/requirements-py37-linux.txt, requirements/out/requirements-py38-linux.txt, requirements/out/requirements-py39-linux.txt, setup.py, support/appimage/AppImageBuilder.yml
This PR add support for producing AppImages as a new format for releases on GNU/Linux.
Due to limitations with the build tools AppImages need to be built on a Debian-based distro (in particular Ubuntu 20.04), as appimage-builder needs apt-get to prepare the AppDir, and the python executable must install packages in the AppDir using the multi-arch directory structure.
Nonetheless the generated AppImages seem to be pretty stable and currently have much less ABI incompatibility issues than the builds generated with pyinstaller.
=> Introduce AppImage support for releases on GNU/Linux

.github/workflows/builds.yml, .github/workflows/tests.yml, README.md
Bintray has been sunset on May 1st 2021, so uploads there are not possible anymore.
This PR drops all artifact uploads to Bintray. Also, since GitHub provides runners for all
supported platform, this moves all the other CI workflows there by adding build workflows
for Windows.
This means that all the infrastructure for the project is now hosted entirely on GitHub.
Old workflows are still in place, but have been disabled.
=> Drop uploads to Bintray and move all ci workflows to GitHub

eddy/ui/file.py, eddy/ui/import_ontology.py, eddy/ui/plugin.py, eddy/ui/preferences.py, eddy/ui/session.py, eddy/ui/welcome.py, eddy/ui/workspace.py
This PR addresses the following issues:
* #145: Addressed by implementing a file dialog that saves and restores its state and geometry between usages (including the last visited folder).
* #142: Addressed by switching the project path to the newly selected file when doing saveAs.
=> State-preserving file dialog and saveAs behaviour

eddy/core/application.py, eddy/core/datatypes/system.py, eddy/core/functions/fsystem.py, eddy/core/functions/path.py, eddy/core/plugin.py
Use appropriate platform-specific locations for storing application configuration and data (currently only includes plugins) instead of a fixed .eddy folder in the user home for every supported platform.
The new paths are the following:
* %APPDATA%\Eddy\plugins for Windows;
* ~/Library/Application Support/Eddy/plugins for macOS;
* $XDG_DATA_HOME/eddy/plugins for Linux (or any XDG desktop).
=> Platform-specific directories for application config and data

eddy/core/exporters/owl2.py
This enables to automatically pre-select the most-appropriate OWL 2
syntax based on the user-specified output file extension during export.
=> Pre-select OWL 2 syntax based on selected output file extension

eddy/core/exporters/metadata.py
Fix the annotation filter being ignored when exporting to csv or xlsx.
Closes #166.
=> Fix annotation filter being ignored on export

eddy/ui/plugin.py
Otherwise on desktop environments where dialogs are rendered frameless (e.g. macOS 11+) the only way to cancel the dialog is to press the ESC key, which is very unintuitive.
See #176
=> Add cancel button to plugin install dialog

eddy.spec
There is some work to do to properly support the dark theme on macOS 10.15+, like preparing a dark variant of the stylesheet and icon set and setting up an auto-detection mechanism.
This PR temporarily disables it for builds using the `NSRequiresAquaSystemAppearance` key so that at least it can be used without forcing the user to switch to a light theme variant.
See #175
=> Opt out of dark theme on macOS

eddy/core/exporters/metadata.py, requirements/in/base.in, requirements/out/requirements-py310-linux.txt, requirements/out/requirements-py310-macos.txt, requirements/out/requirements-py310-winnt.txt, requirements/out/requirements-py37-linux.txt, requirements/out/requirements-py37-macos.txt, requirements/out/requirements-py37-winnt.txt, requirements/out/requirements-py38-linux.txt, requirements/out/requirements-py38-macos.txt, requirements/out/requirements-py38-winnt.txt, requirements/out/requirements-py39-linux.txt, requirements/out/requirements-py39-macos.txt, requirements/out/requirements-py39-winnt.txt, setup.py
This change only affects the annotations exporter, and is required in anticipation of the creation of a metadata loader.
Given that xlsxwriter does not support reading existing Excel files, it is better to migrate to a different library, since carrying two dependencies just for working with Excel files is a bit overkill.
=> Migrate from XlsxWriter to openpyxl

eddy/plugins/ontology-importer/ontology_importer.py, eddy/plugins/ontology-importer/plugin.spec, eddy/ui/forms.py
As specified in #203. For the moment it lacks the migration infrastructure but is is enough to set the initial version and avoiding opening a newer version with a previous version of the plugin.
=> Initial version of import database versioning

.github/workflows/builds.yml
Looks like dmgbuild 1.6.0+ fixes the issues with macOS 11 and later so we can finally upgrade from the deprecated images for the builds.
=> Upgrade to macOS 11 for CI builds

eddy/core/exporters/owl2.py
This removal was mostly a hack from the time when entity IRIs where entered with newlines in them for formatting purposes, and automatically-generated annotations like `rdfs:label` where also getting these newlines.
=> Preserve newlines in literals during OWL 2 export

eddy/core/exporters/graphol_iri.py, eddy/core/items/nodes/literal.py
Fixes an issue where the label of literal nodes loaded from a graphol project file would get the default 'Empty' text rather than the proper literal value.
This also fixes an issue existing since at least v3.1 where editing and saving the literal value without any change would result in a duplicate label getting generated for the node, and an incompatibility
of the graphol exporter with python 3.10.
=> Fix label of literal nodes not getting updated on project load

eddy/core/commands/project.py, eddy/plugins/project-explorer/project_explorer.py, eddy/ui/forms.py, eddy/ui/session.py
This is an alternative to #264 to keep the project name property for the time being and allow it to be renamed from the UI. 
The fact is that it is not clear how to deal with the case where the ontology IRI has not short form (think of suggested save file names for which we currently use the project name).
We can consider again removing it when we figure this out.
=> Project rename action

eddy/plugins/ontology-importer/ontology_importer.py
This is a proposal fix for #270 by setting the anon ontology IRI to be the file URI (e.g. `file:///path/to/my/ontology.owl`).
=> [Ontology Importer] Allow importing anonymous owl ontologies

eddy/core/common.py, eddy/core/diagram.py, eddy/core/exporters/metadata.py, eddy/core/factory.py, eddy/core/plugin.py, eddy/core/project.py, eddy/ui/iri.py
Now that python 3.7 is required to run Eddy, we can start making use of [PEP 563](https://www.python.org/dev/peps/pep-0563/) postponed evaluation of annotations.
=> PEP 563 annotations

eddy/core/exporters/graphol_iri.py, eddy/ui/annotation.py, eddy/ui/ontology.py
Changes related to the support of non-graphical IRIs in a graphol project, such as the ones
that can result by the inclusion of an external RDF dataset.
=> Non-graphical IRIs in the project
